# Generated by Django 3.1.5 on 2021-01-26 04:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geo_json_file', models.FileField(blank=True, null=True, upload_to='')),
                ('geo_collection', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geo_json_file', models.FileField(blank=True, null=True, upload_to='')),
                ('geo_collection', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='region_builder.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
